import functions,os,datetime
os.system("cls")
name = ""
center = 0
archive = functions.main_interface()
os.system("cls")
if archive == 0:
    functions.dialog_box([], "你好！让你久等了！（按回车键继续）")
    functions.dialog_box([], "欢迎来到精灵宝可梦的世界！")
    functions.dialog_box([], "我是小田卷。")
    functions.dialog_box([], "人们都称我为\n宝可梦博士。")
    functions.dialog_box([], "这就是被我们称为\n“宝可梦”的生物（掏出精灵球）")
    functions.dialog_box([], "这个世界广泛存在着精灵宝可梦，\n人们也管它们叫宝可梦。")
    functions.dialog_box([], "人们和宝可梦一起玩耍，\n互相帮助，并且成为了好伙伴。")
    functions.dialog_box([], "有时候，我们与它们\n宝可梦一起战斗。")
    functions.dialog_box([], "遗憾的是，我们对它们\n并不是很了解。")
    functions.dialog_box([], "事实上，宝可梦身上\n还有很多很多秘密。")
    functions.dialog_box([], "为了揭开宝可梦的秘密，\n我倾注了毕生心血研究它们。\n来实现我一生中最大的愿望")
    functions.dialog_box([], "那么请问？")
    gender = functions.dialog_box(["男", "女"], "你是男孩？还是女孩？")
    while name == "":
        os.system("cls")
        print("那么，请告诉我你的名字吧！")
        name = input()
    functions.dialog_box([], "啊，没错！")
    functions.dialog_box([], f"你就是刚搬到\n未白镇来的{name}啊。我知道了！")
    functions.dialog_box([], "好的，准备好了吗？")
    functions.dialog_box([], "振奋人心的冒险即将展开。")
    functions.dialog_box([], "鼓起勇气，迈向宝可梦的世界吧！\n那里孕育着梦想，\n充满着刺激，还会遇到新的朋友！")
    functions.dialog_box([], "当然，我对你充满了期待。\n到我的宝可梦研究所来见我吧。")
    functions.location_cutscenes("未白镇")
    functions.dialog_box([], f"妈妈：{name}，我们到了，宝贝！")
    functions.dialog_box([], "跟我们的行李一起挤在车厢里\n很累吧？")
    functions.dialog_box([], "喜欢吗？\n这是我们的新家！")
    functions.dialog_box([], "虽然房子看上去有点老旧，\n但你不觉得住起来应该很舒适吗？")
    functions.dialog_box([], f"而且这次也有你自己的房间了，{name}！我们先进屋吧。")
    functions.location_cutscenes("新家 一楼")
    functions.dialog_box([], f"妈妈：怎么样，{name}？\n这儿不错吧？")
    functions.dialog_box([], "搬家公司的宝可梦帮我们把东西\n都搬进来，还会帮忙打扫房间。真方便！")
    functions.dialog_box([], f"{name}，你的房间在楼上，去看看吧，宝贝！")
    functions.dialog_box([], "爸爸给你买了个钟，\n这样你就能知道时间了。别忘了调钟啊！")
    functions.dialog_box([], "（过动猿在打扫房间）")
    functions.location_cutscenes("新家 二楼")
    functions.dialog_box([], "钟停了，把它调好吧！")
    input(f"现在是{datetime.datetime.now().hour}点，请你再次输入")
    os.system("cls")
    functions.dialog_box([], f"妈妈：{name}，喜欢你的\n新房间吗？")
    functions.dialog_box([], "好！房间都清理干净了！")
    functions.dialog_box([], "楼下也\n整理完毕了，")
    functions.dialog_box([], "让宝可梦搬家真方便啊！")
    functions.dialog_box([], "啊，最好是看看你桌子上的东西\n是不是都齐了。")
    choice = functions.dialog_box(["NGC", "笔记"], "你在房间里发现了：")
    if choice == 0:
        functions.dialog_box([], "这是NGC，")
        functions.dialog_box([], "上面连着个GBR\n当做手柄。")
    elif choice == 1:
        functions.dialog_box([], f"{name}翻开笔记。")
        functions.dialog_box([], "冒险须知第一条：QWQ")
        functions.dialog_box([], "冒险须知第二条：保存选项可以记录")
        functions.dialog_box([], "后面是空白")
    functions.dialog_box(["去一楼"], "接下来你要干什么？")
    
